server:
  port: 8005

mall-top:
  item:
    url: http://127.0.0.1:8002/item/

spring:
  application:
    name: mall-top-microservice-order

eureka:
  client:
    register-with-eureka: true #是否将自己注册到Eureka服务中,本身就是所有无需注册
    fetch-registry:  true
    service-url: #是否从Eureka中获取注册信息  #Eureka客户端和Eureka服务器进行交互的地址
      defaultZone: http://abcd:123456@127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #是否将自己的ip地址注册到Eureka服务中